### ISSUE TITLE
tags for MELPA Stable

### ISSUE THREAD

**Issue by dunn** [realgud/realgud-pry#2]
If/when this and other realgud plugins (byebug, etc.) are stable enough, it'd be awesome to have tagged releases so they show up in MELPA Stable!

**Comment by rocky** [comment]
Here's the problem: I've never been a user of pry, or byebug and so on to feel that it would warrant my time to worry about these.  

If however someone else such as yourself comes along and wants to commit time, care, and feeding if there's a problem, then okay, that person can make such a decision, and take consequences for the result.

Nowadays, the amount of time I spend on a project, especially on those I don't regularly use, is related to the rating. Judging from the ratings, no one has indicated any interest in this (including you). 

Yes, there's a chicken and egg problem with this approach: not working on a project isn't likely to get it to be used by others.. But again, at this point there are so many other projects that show more popularity, that I use, or am interested in, that projects like this don't warrant my effort.  And quite honestly, I wouldn't know if this is "stable" or a pile of crap.

**Comment by dunn** [comment]
That's totally fair.  I'll close this for now, and if I find I'm able to contribute I might bring it up again down the road.
