### ISSUE TITLE
NoMethodError: undefined method `annotate' for main:Object

### ISSUE THREAD

**Issue by Vonfry** [realgud/realgud-pry#3]
```
set annotate 1
NoMethodError: undefined method `annotate' for main:Object
from (pry):5:in `__pry__'
```

realgud-pry uses it at [here](https://github.com/realgud/realgud-pry/blob/9b3834048fcbc16827c55af38f8cfef0cf6533da/pry/pry.el#L82)

**Comment by Vonfry** [comment]
byebug and pry have been installed. And in byebug, set hasn't annotate option.

**Comment by rocky** [comment]
> byebug and pry have been installed. And in byebug, set hasn't annotate option.

Ok. Try removing the `if` in the link you cite. If things then work, then put in a PR.
